// Generated by convex-typegen — do not edit by hand.
// Repo: https://github.com/JamalLyons/convex-typegen
// Regenerated on each `cargo build` when inputs change (see your `build.rs` rerun-if-changed lines).

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

use convex_typegen::prelude::*;

#[derive(Debug, Clone)]
pub struct GamesTable {
    pub win_count: f64,
    pub loss_count: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct GetGameArgs {
    pub logData: Option<bool>,
}

impl GetGameArgs {
    pub const FUNCTION_PATH: &'static str = "games:getGame";
}

impl std::convert::TryFrom<GetGameArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
    type Error = ConvexJsonError;

    fn try_from(_args: GetGameArgs) -> Result<Self, Self::Error> {
        let mut map = std::collections::BTreeMap::new();
        if let Some(__v) = _args.logData {
            map.insert("logData".to_string(), convex_typegen::serde_json::to_value(__v)?);
        }
        Ok(map)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct WinGameArgs {
}

impl WinGameArgs {
    pub const FUNCTION_PATH: &'static str = "games:winGame";
}

impl std::convert::TryFrom<WinGameArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
    type Error = ConvexJsonError;

    fn try_from(_args: WinGameArgs) -> Result<Self, Self::Error> {
        Ok(std::collections::BTreeMap::new())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct LossGameArgs {
}

impl LossGameArgs {
    pub const FUNCTION_PATH: &'static str = "games:lossGame";
}

impl std::convert::TryFrom<LossGameArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
    type Error = ConvexJsonError;

    fn try_from(_args: LossGameArgs) -> Result<Self, Self::Error> {
        Ok(std::collections::BTreeMap::new())
    }
}

