// Generated by convex-typegen — do not edit by hand.
// Repo: https://github.com/JamalLyons/convex-typegen
// Regenerated on each `cargo build` when inputs change (see your `build.rs` rerun-if-changed lines).

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

use convex_typegen::prelude::*;

#[derive(Debug, Clone)]
pub struct GamesTable {
    pub win_count: f64,
    pub loss_count: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct GamesGetGameArgs {
    pub logData: Option<bool>,
}

impl GamesGetGameArgs {
    pub const FUNCTION_PATH: &'static str = "games:getGame";
}

impl std::convert::TryFrom<GamesGetGameArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
    type Error = ConvexJsonError;

    fn try_from(_args: GamesGetGameArgs) -> Result<Self, Self::Error> {
        let mut map = std::collections::BTreeMap::new();
        if let Some(__v) = _args.logData {
            map.insert("logData".to_string(), convex_typegen::serde_json::to_value(__v)?);
        }
        Ok(map)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct GamesWinGameArgs {}

impl GamesWinGameArgs {
    pub const FUNCTION_PATH: &'static str = "games:winGame";
}

impl std::convert::TryFrom<GamesWinGameArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
    type Error = ConvexJsonError;

    fn try_from(_args: GamesWinGameArgs) -> Result<Self, Self::Error> {
        Ok(std::collections::BTreeMap::new())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct GamesLossGameArgs {}

impl GamesLossGameArgs {
    pub const FUNCTION_PATH: &'static str = "games:lossGame";
}

impl std::convert::TryFrom<GamesLossGameArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
    type Error = ConvexJsonError;

    fn try_from(_args: GamesLossGameArgs) -> Result<Self, Self::Error> {
        Ok(std::collections::BTreeMap::new())
    }
}
