//! Golden tests for stable codegen output.

use std::fs;

use convex_typegen::config::Configuration;
use convex_typegen::generate;
use tempfile::tempdir;

const MINIMAL_SCHEMA: &str = r#"
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
    items: defineTable({ name: v.string() }),
});
"#;

const MINIMAL_FN: &str = r#"
import { query } from "./_generated/server";
import { v } from "convex/values";

export const getItem = query({
    args: { id: v.string() },
    handler: async (_ctx, _args) => null,
});
"#;

const DUP_MOD_A: &str = r#"
import { query } from "./_generated/server";
import { v } from "convex/values";

export const list = query({
    args: { a: v.number() },
    handler: async (_ctx, _args) => null,
});
"#;

const DUP_MOD_B: &str = r#"
import { query } from "./_generated/server";
import { v } from "convex/values";

export const list = query({
    args: { b: v.string() },
    handler: async (_ctx, _args) => null,
});
"#;

const NESTED_OBJECT_SCHEMA: &str = r#"
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
    projects: defineTable({
        settings: v.object({
            theme: v.string(),
            notifyEmail: v.boolean(),
        }),
    }),
});
"#;

const NESTED_OBJECT_FN: &str = r#"
import { action } from "./_generated/server";
import { v } from "convex/values";

export const integrationsMirror = action({
    args: {
        flags: v.object({
            verbose: v.boolean(),
            trace: v.boolean(),
        }),
    },
    handler: async (_ctx, _args) => null,
});
"#;

const OPTIONAL_FN: &str = r#"
import { mutation } from "./_generated/server";
import { v } from "convex/values";

export const update = mutation({
    args: { flag: v.optional(v.boolean()) },
    handler: async (_ctx, _args) => null,
});
"#;

fn run_generate(schema: &str, extra_files: &[(&str, &str)]) -> String
{
    let tmp = tempdir().unwrap();
    let convex = tmp.path().join("convex");
    fs::create_dir_all(&convex).unwrap();
    let schema_path = convex.join("schema.ts");
    fs::write(&schema_path, schema).unwrap();
    for (name, body) in extra_files {
        fs::write(convex.join(name), body).unwrap();
    }
    let out = tmp.path().join("out.rs");
    let cfg = Configuration {
        schema_path,
        out_file: out.clone(),
        convex_dir: convex,
        function_paths: Vec::new(),
    };
    generate(cfg).unwrap();
    fs::read_to_string(&out).unwrap()
}

#[test]
fn golden_minimal_schema_and_function()
{
    let body = run_generate(MINIMAL_SCHEMA, &[("api.ts", MINIMAL_FN)]);
    insta::assert_snapshot!(body, @r#"
    // Generated by convex-typegen — do not edit by hand.
    // Repo: https://github.com/JamalLyons/convex-typegen
    // Regenerated on each `cargo build` when inputs change (see your `build.rs` rerun-if-changed lines).

    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(dead_code)]

    use convex_typegen::prelude::*;

    #[derive(Debug, Clone)]
    pub struct ItemsTable {
        pub name: String,
    }

    #[derive(Debug, Clone, Serialize, Deserialize)]
    #[serde(crate = "convex_typegen::serde")]
    pub struct ApiGetItemArgs {
        pub id: String,
    }

    impl ApiGetItemArgs {
        pub const FUNCTION_PATH: &'static str = "api:getItem";
    }

    impl std::convert::TryFrom<ApiGetItemArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
        type Error = ConvexJsonError;

        fn try_from(_args: ApiGetItemArgs) -> Result<Self, Self::Error> {
            let mut map = std::collections::BTreeMap::new();
            map.insert("id".to_string(), convex_typegen::serde_json::to_value(_args.id)?);
            Ok(map)
        }
    }

    "#);
}

#[test]
fn golden_duplicate_exports_unique_struct_names()
{
    let body = run_generate(MINIMAL_SCHEMA, &[("mod_a.ts", DUP_MOD_A), ("mod_b.ts", DUP_MOD_B)]);
    assert!(body.contains("pub struct ModAListArgs"));
    assert!(body.contains("pub struct ModBListArgs"));
    assert!(!body.contains("pub struct ListArgs"));
}

#[test]
fn golden_named_nested_object_structs()
{
    let body = run_generate(NESTED_OBJECT_SCHEMA, &[("integrations.ts", NESTED_OBJECT_FN)]);
    assert!(body.contains("pub struct ProjectsSettings"));
    assert!(body.contains("pub settings: ProjectsSettings"));
    assert!(body.contains("pub struct IntegrationsMirrorFlags"));
    assert!(body.contains("pub flags: IntegrationsMirrorFlags"));
}

#[test]
fn golden_optional_root_omits_key_in_try_from()
{
    let body = run_generate(MINIMAL_SCHEMA, &[("opts.ts", OPTIONAL_FN)]);
    assert!(body.contains("pub struct OptsUpdateArgs"));
    assert!(body.contains("if let Some(__v) = _args.flag"));
}
