// Generated by convex-typegen — do not edit by hand.
// Repo: https://github.com/JamalLyons/convex-typegen
// Regenerated on each `cargo build` when inputs change (see your `build.rs` rerun-if-changed lines).

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

use convex_typegen::prelude::*;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct IntegrationsMirrorFlags {
    pub trace: bool,
    pub verbose: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct ProjectsSettings {
    pub notifyEmail: bool,
    pub theme: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct TasksSearchFilter {
    pub minPriority: Option<ConvexJsonValue>,
    pub projectId: String,
}

#[derive(Debug, Clone)]
pub enum UsersRole {
    Admin,
    Member,
    Viewer,
}

#[derive(Debug, Clone)]
pub enum ProjectsStatus {
    Draft,
    Active,
    Archived,
}

#[derive(Debug, Clone)]
pub enum TasksPriority {
    P0,
    P1,
    P2,
}

#[derive(Debug, Clone)]
pub struct UsersTable {
    pub email: String,
    pub displayName: String,
    pub role: UsersRole,
    pub metadata: std::collections::HashMap<String, String>,
    pub avatarBytes: Option<Vec<u8>>,
    pub externalId: Option<String>,
    pub score: Option<i64>,
    pub isActive: bool,
}

#[derive(Debug, Clone)]
pub struct TeamsTable {
    pub name: String,
    pub slug: String,
    pub ownerUserId: String,
    pub createdAt: f64,
}

#[derive(Debug, Clone)]
pub struct ProjectsTable {
    pub teamId: String,
    pub title: String,
    pub status: ProjectsStatus,
    pub tags: Vec<String>,
    pub settings: ProjectsSettings,
    pub budget: Option<f64>,
}

#[derive(Debug, Clone)]
pub struct TasksTable {
    pub projectId: String,
    pub title: String,
    pub priority: TasksPriority,
    pub assigneeUserId: Option<String>,
    pub payload: ConvexJsonValue,
    pub dueAt: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct IntegrationsMirrorArgs {
    pub body: String,
    pub numbers: Vec<f64>,
    pub flags: IntegrationsMirrorFlags,
    pub mode: ConvexJsonValue,
    pub extra: Option<std::collections::HashMap<String, String>>,
}

impl IntegrationsMirrorArgs {
    pub const FUNCTION_PATH: &'static str = "integrations:integrationsMirror";
}

impl std::convert::TryFrom<IntegrationsMirrorArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
    type Error = ConvexJsonError;

    fn try_from(_args: IntegrationsMirrorArgs) -> Result<Self, Self::Error> {
        let mut map = std::collections::BTreeMap::new();
        map.insert("body".to_string(), convex_typegen::serde_json::to_value(_args.body)?);
        map.insert("numbers".to_string(), convex_typegen::serde_json::to_value(_args.numbers)?);
        map.insert("flags".to_string(), convex_typegen::serde_json::to_value(_args.flags)?);
        map.insert("mode".to_string(), convex_typegen::serde_json::to_value(_args.mode)?);
        if let Some(__v) = _args.extra {
            map.insert("extra".to_string(), convex_typegen::serde_json::to_value(__v)?);
        }
        Ok(map)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct ProjectsListByTeamArgs {
    pub teamId: String,
    pub statusFilter: Option<ConvexJsonValue>,
}

impl ProjectsListByTeamArgs {
    pub const FUNCTION_PATH: &'static str = "projects:projectsListByTeam";
}

impl std::convert::TryFrom<ProjectsListByTeamArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
    type Error = ConvexJsonError;

    fn try_from(_args: ProjectsListByTeamArgs) -> Result<Self, Self::Error> {
        let mut map = std::collections::BTreeMap::new();
        map.insert("teamId".to_string(), convex_typegen::serde_json::to_value(_args.teamId)?);
        if let Some(__v) = _args.statusFilter {
            map.insert("statusFilter".to_string(), convex_typegen::serde_json::to_value(__v)?);
        }
        Ok(map)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct ProjectsUpdateTagsArgs {
    pub projectId: String,
    pub tags: Vec<String>,
}

impl ProjectsUpdateTagsArgs {
    pub const FUNCTION_PATH: &'static str = "projects:projectsUpdateTags";
}

impl std::convert::TryFrom<ProjectsUpdateTagsArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
    type Error = ConvexJsonError;

    fn try_from(_args: ProjectsUpdateTagsArgs) -> Result<Self, Self::Error> {
        let mut map = std::collections::BTreeMap::new();
        map.insert("projectId".to_string(), convex_typegen::serde_json::to_value(_args.projectId)?);
        map.insert("tags".to_string(), convex_typegen::serde_json::to_value(_args.tags)?);
        Ok(map)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct TasksSearchArgs {
    pub filter: TasksSearchFilter,
    pub limit: Option<f64>,
}

impl TasksSearchArgs {
    pub const FUNCTION_PATH: &'static str = "tasks:tasksSearch";
}

impl std::convert::TryFrom<TasksSearchArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
    type Error = ConvexJsonError;

    fn try_from(_args: TasksSearchArgs) -> Result<Self, Self::Error> {
        let mut map = std::collections::BTreeMap::new();
        map.insert("filter".to_string(), convex_typegen::serde_json::to_value(_args.filter)?);
        if let Some(__v) = _args.limit {
            map.insert("limit".to_string(), convex_typegen::serde_json::to_value(__v)?);
        }
        Ok(map)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct TasksCreateArgs {
    pub projectId: String,
    pub title: String,
    pub priority: ConvexJsonValue,
    pub assigneeUserId: Option<String>,
    pub payload: Option<ConvexJsonValue>,
    pub dueAt: Option<f64>,
}

impl TasksCreateArgs {
    pub const FUNCTION_PATH: &'static str = "tasks:tasksCreate";
}

impl std::convert::TryFrom<TasksCreateArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
    type Error = ConvexJsonError;

    fn try_from(_args: TasksCreateArgs) -> Result<Self, Self::Error> {
        let mut map = std::collections::BTreeMap::new();
        map.insert("projectId".to_string(), convex_typegen::serde_json::to_value(_args.projectId)?);
        map.insert("title".to_string(), convex_typegen::serde_json::to_value(_args.title)?);
        map.insert("priority".to_string(), convex_typegen::serde_json::to_value(_args.priority)?);
        if let Some(__v) = _args.assigneeUserId {
            map.insert("assigneeUserId".to_string(), convex_typegen::serde_json::to_value(__v)?);
        }
        if let Some(__v) = _args.payload {
            map.insert("payload".to_string(), convex_typegen::serde_json::to_value(__v)?);
        }
        if let Some(__v) = _args.dueAt {
            map.insert("dueAt".to_string(), convex_typegen::serde_json::to_value(__v)?);
        }
        Ok(map)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct TeamsListByOwnerArgs {
    pub ownerUserId: String,
}

impl TeamsListByOwnerArgs {
    pub const FUNCTION_PATH: &'static str = "teams:teamsListByOwner";
}

impl std::convert::TryFrom<TeamsListByOwnerArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
    type Error = ConvexJsonError;

    fn try_from(_args: TeamsListByOwnerArgs) -> Result<Self, Self::Error> {
        let mut map = std::collections::BTreeMap::new();
        map.insert("ownerUserId".to_string(), convex_typegen::serde_json::to_value(_args.ownerUserId)?);
        Ok(map)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct TeamsCreateArgs {
    pub name: String,
    pub slug: String,
    pub ownerUserId: String,
    pub createdAt: Option<f64>,
}

impl TeamsCreateArgs {
    pub const FUNCTION_PATH: &'static str = "teams:teamsCreate";
}

impl std::convert::TryFrom<TeamsCreateArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
    type Error = ConvexJsonError;

    fn try_from(_args: TeamsCreateArgs) -> Result<Self, Self::Error> {
        let mut map = std::collections::BTreeMap::new();
        map.insert("name".to_string(), convex_typegen::serde_json::to_value(_args.name)?);
        map.insert("slug".to_string(), convex_typegen::serde_json::to_value(_args.slug)?);
        map.insert("ownerUserId".to_string(), convex_typegen::serde_json::to_value(_args.ownerUserId)?);
        if let Some(__v) = _args.createdAt {
            map.insert("createdAt".to_string(), convex_typegen::serde_json::to_value(__v)?);
        }
        Ok(map)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct UsersGetByEmailArgs {
    pub email: String,
    pub includeInactive: Option<bool>,
}

impl UsersGetByEmailArgs {
    pub const FUNCTION_PATH: &'static str = "users:usersGetByEmail";
}

impl std::convert::TryFrom<UsersGetByEmailArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
    type Error = ConvexJsonError;

    fn try_from(_args: UsersGetByEmailArgs) -> Result<Self, Self::Error> {
        let mut map = std::collections::BTreeMap::new();
        map.insert("email".to_string(), convex_typegen::serde_json::to_value(_args.email)?);
        if let Some(__v) = _args.includeInactive {
            map.insert("includeInactive".to_string(), convex_typegen::serde_json::to_value(__v)?);
        }
        Ok(map)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct UsersGetProfileArgs {
    pub userId: String,
    pub withBytes: Option<bool>,
}

impl UsersGetProfileArgs {
    pub const FUNCTION_PATH: &'static str = "users:usersGetProfile";
}

impl std::convert::TryFrom<UsersGetProfileArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
    type Error = ConvexJsonError;

    fn try_from(_args: UsersGetProfileArgs) -> Result<Self, Self::Error> {
        let mut map = std::collections::BTreeMap::new();
        map.insert("userId".to_string(), convex_typegen::serde_json::to_value(_args.userId)?);
        if let Some(__v) = _args.withBytes {
            map.insert("withBytes".to_string(), convex_typegen::serde_json::to_value(__v)?);
        }
        Ok(map)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct UsersCreateArgs {
    pub email: String,
    pub displayName: String,
    pub role: ConvexJsonValue,
    pub metadata: Option<std::collections::HashMap<String, String>>,
    pub score: Option<i64>,
    pub avatarBytes: Option<Vec<u8>>,
}

impl UsersCreateArgs {
    pub const FUNCTION_PATH: &'static str = "users:usersCreate";
}

impl std::convert::TryFrom<UsersCreateArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
    type Error = ConvexJsonError;

    fn try_from(_args: UsersCreateArgs) -> Result<Self, Self::Error> {
        let mut map = std::collections::BTreeMap::new();
        map.insert("email".to_string(), convex_typegen::serde_json::to_value(_args.email)?);
        map.insert("displayName".to_string(), convex_typegen::serde_json::to_value(_args.displayName)?);
        map.insert("role".to_string(), convex_typegen::serde_json::to_value(_args.role)?);
        if let Some(__v) = _args.metadata {
            map.insert("metadata".to_string(), convex_typegen::serde_json::to_value(__v)?);
        }
        if let Some(__v) = _args.score {
            map.insert("score".to_string(), convex_typegen::serde_json::to_value(__v)?);
        }
        if let Some(__v) = _args.avatarBytes {
            map.insert("avatarBytes".to_string(), convex_typegen::serde_json::to_value(__v)?);
        }
        Ok(map)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct WorkspaceSeedIfEmptyArgs {
}

impl WorkspaceSeedIfEmptyArgs {
    pub const FUNCTION_PATH: &'static str = "workspace:workspaceSeedIfEmpty";
}

impl std::convert::TryFrom<WorkspaceSeedIfEmptyArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
    type Error = ConvexJsonError;

    fn try_from(_args: WorkspaceSeedIfEmptyArgs) -> Result<Self, Self::Error> {
        Ok(std::collections::BTreeMap::new())
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(crate = "convex_typegen::serde")]
pub struct WorkspaceSummaryArgs {
}

impl WorkspaceSummaryArgs {
    pub const FUNCTION_PATH: &'static str = "workspace:workspaceSummary";
}

impl std::convert::TryFrom<WorkspaceSummaryArgs> for std::collections::BTreeMap<String, ConvexJsonValue> {
    type Error = ConvexJsonError;

    fn try_from(_args: WorkspaceSummaryArgs) -> Result<Self, Self::Error> {
        Ok(std::collections::BTreeMap::new())
    }
}

