[package]
name = "basic"
version = "0.1.0"
edition = "2021"

[dependencies]
convex = "0.9.0"
dotenvy = "0.15.7"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"
tokio = { version = "1.43.1", features = ["full"] }
rand = "0.8"
convex-typegen = { path = "../../" }

[build-dependencies]
convex-typegen = { path = "../../" }
